.TH "lud" "1" "" "Michele Bini"
.SH NAME
lud \- Experimental OpenUDC client
.SH SYNOPSIS
.PP
\fClud\fP
.SH DESCRIPTION
.PP
**lud** is an experimental implementation of an OpenUDC client.
.PP
It can be currently used to:
.RS 4
.IP \(bu 4
\&create your identity for the OpenUDC web of trust (udid2)
.IP \(bu 4
\&registering that identity for participating to the monetary
community.
.RE
.PP
Before running \fClud\fP you should have created your GnuPG (\fCgpg\fP)
key pair.
.PP
The program functions interactively and presents a menu to the user.
.PP
An Internet connection is required, for most of the functionality.
.SH OPTIONS
.PP
No options are currently documented.
.SH SEE ALSO
.PP
\fCgpg2\fP (1), \fCseahorse\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


